Upgrade to .NET 4.6.1
codesmithtools/CodeSmith.Data pull request #1
Opened 2016-10-19 17:05 UTC by jayhilden

- Update to the latest version of .NET (pre-CORE)
- Update to Visual Studio 2015
- Update build directory to the standard `/bin/release`

2016-10-21 16:08 UTC, niemyjski commented
Is there any specific reason for changing this to 4.6.1? You can target 4.5 in a 4.6.1 project?

2016-10-21 16:29 UTC, jayhilden commented
The main reason is that 4.5 has reached end of life.

https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

So really, all projects should be updated to .NET 4.6.x and/or .NET CORE

2016-10-21 22:22 UTC, niemyjski commented
We'd be more than happy to accept an updated pr, that adds a build target for 4.6 but we still have to have support for existing versions as not everyone updates :\. We still are supporting users on VS2010.

2016-10-21 22:23 UTC, niemyjski requested changes

2016-10-21 22:23 UTC, niemyjski commented on Source/CodeSmith.Data/CodeSmith.Data.csproj
> +    <OutputPath>bin\Debug\</OutputPath>
Can you revert this change, we source import this git branch and do builds.

2016-10-21 22:23 UTC, niemyjski commented on Source/CodeSmith.Data/CodeSmith.Data.csproj
> +    <DocumentationFile>bin\Debug\CodeSmith.Data.XML</DocumentationFile>
Can you revert this change, we source import this git branch and do builds.

2016-10-21 22:23 UTC, niemyjski commented on Source/CodeSmith.Data/CodeSmith.Data.csproj
> +    <OutputPath>bin\Release\</OutputPath>
Can you revert this change, we source import this git branch and do builds.

2016-10-21 22:23 UTC, niemyjski commented on Source/CodeSmith.Data/CodeSmith.Data.csproj
> +    <DocumentationFile>bin\Release\CodeSmith.Data.XML</DocumentationFile>
Can you revert this change, we source import this git branch and do builds.

2016-10-21 22:23 UTC, niemyjski commented on Source/CodeSmith.Data/CodeSmith.Data.csproj
>    <ItemGroup>
Can you revert this change, we source import this git branch and do builds.

2017-01-13 19:56 UTC, niemyjski commented
At this time, we have no intention of merging this pull request with out the requested changes being made. Also, the source for CodeSmith.Data.Linq should be open source. Please feel free to reopen the pull request with the suggested changes

2017-01-13 19:56 UTC, closed without merging